name: Build Release

on: 
  workflow_dispatch:
  push:
    paths:
      - 'Packages/io.github.ykysnk.yky-toolkit/package.json'

jobs:

  # Validate Repository Configuration
  config:
    runs-on: ubuntu-latest
    outputs:
      config_package: ${{ steps.config_package.outputs.configPackage }}
    steps:
      
      # Ensure that required repository variable has been created for the Package
      - name: Validate Package Config
        id: config_package
        run: |
          if [ "${{ vars.PACKAGE_NAME }}" != "" ]; then
            echo "configPackage=true" >> $GITHUB_OUTPUT;
          else
            echo "configPackage=false" >> $GITHUB_OUTPUT;
          fi

  # Build and release the Package
  # If the repository is not configured properly, this job will be skipped
  build:
    needs: config
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      packagePath: Packages/${{ vars.PACKAGE_NAME }}
    if: needs.config.outputs.config_package == 'true'
    steps:

      # Checkout Local Repository
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Get the Package version based on the package.json file
      - name: Get Version
        id: version
        uses: zoexx/github-action-json-file-properties@b9f36ce6ee6fe2680cd3c32b2c62e22eade7e590
        with:
          file_path: "${{ env.packagePath }}/package.json"
          prop_path: "version"
      
      # Configure the Environment Variables needed for releasing the Package
      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ vars.PACKAGE_NAME }}-${{ steps.version.outputs.value }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ vars.PACKAGE_NAME }}-${{ steps.version.outputs.value }}.unitypackage" >> $GITHUB_ENV
          echo "version=${{ steps.version.outputs.value }}" >> $GITHUB_ENV

      # Zip the Package for release
      - name: Create Package Zip
        working-directory: "${{ env.packagePath }}"
        run: zip -r "${{ github.workspace }}/${{ env.zipFile }}" .
      
      # Build a list of .meta files for future use
      - name: Track Package Meta Files
        run: find "${{ env.packagePath }}/" -name \*.meta >> metaList
      
      # Make a UnityPackage version of the Package for release
      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@v1.2.3
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList
      
      # Make a release tag of the version from the package.json file 
      - name: Create Tag
        id: tag_version
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ env.version }}"

      - name: Install `typos-cli` from `crates.io`
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typos-cli

      - name: Pull changes
        run: git pull

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: --verbose --config-url https://raw.githubusercontent.com/T2PeNBiX99wcoxKv3A4g/Git-Cliff-Template/refs/heads/master/cliff-vpm.toml
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Set git user
        uses: fregante/setup-git-user@v2

      - name: Check for changes
        run: git status

      - name: Stage changed files
        run: git add .

      - name: Commit changed files
        run: "git commit -m 'Action: Update `CHANGELOG.md`'"

      - name: Fetch from main
        run: git fetch origin main

      - name: Push code to main
        run: git push origin main

      - name: Pull changes
        run: git pull

      - name: Generate a release body
        uses: orhun/git-cliff-action@v4
        id: git-cliff2
        with:
          args: --verbose --latest --strip header --config-url https://raw.githubusercontent.com/T2PeNBiX99wcoxKv3A4g/Git-Cliff-Template/refs/heads/master/cliff-vpm.toml
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}
      
      # Publish the Release to GitHub
      - name: Make Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            ${{ env.packagePath }}/package.json
          tag_name: ${{ env.version }}
          body: ${{ steps.git-cliff2.outputs.content }}
